eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka:8060/eureka/
server:
  port: 8080
spring:
  application:
    name: sweetpotato