declare
      num number;
begin
    select count(1) into num from user_tables where table_name = upper('test_user') ;
    if num > 0 then
        execute immediate 'drop table test_user';
    end if;
		execute immediate 'create table test_user
		(
			id number generated by default on null as identity,
			username varchar2(12) not null,
			password varchar2(32) not null,
			primary key (id)
		)';
		execute immediate 'insert into test_user values (1, ''testuser'', ''123456'')';
		execute immediate 'insert into test_user values (2, ''test'', ''234567'')';
end;